spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  cloud:
    gcp:
      credentials:
        default-scopes: ${GOOGLE_APPLICATION_CREDENTIALS}
      storage:
        project-id: ${GOOGLE_PROJECT_ID}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

firebase:
  credential: ${FIREBASE_CREDENTIALS}